{{- if eq (include "scout.shouldDeploy" .) "true" }}
{{- if .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scout-rolebinding
  labels:
    {{- include "scout.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "scout.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: scout-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
