{{- if eq true .Values.cloudOne.jobManager.enabled }}
{{- if eq true .Values.cloudOne.vulnerabilityScanning.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: job-manager-role
  labels:
    {{- include "jobManager.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  - batch
  resources:
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: job-manager-rolebinding
  labels:
    {{- include "jobManager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: job-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "jobManager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}