{{- if eq true .Values.cloudOne.runtimeSecurity.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: k8s-metacollector-role
  labels:
    {{- include "k8sMetaCollector.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  - namespaces
  - pods
  - replicationcontrollers
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-metacollector-rolebinding
  labels:
    {{- include "k8sMetaCollector.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-metacollector-role
subjects:
- kind: ServiceAccount
  name: {{ include "k8sMetaCollector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
