{{- if eq true .Values.cloudOne.oversight.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "oversight.labels" . | nindent 4 }}
  name: trendmicro-oversight-controller
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ default 1 .Values.replicas.oversight }}
  selector:
    matchLabels:
      {{- include "oversight.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/auth: {{ include "container.security.auth.secret" . | sha256sum }}
        checksum/cert: {{ include (print $.Template.BasePath "/kube-rbac-proxy-cert.yaml") . | sha256sum }}
{{- with (default .Values.podAnnotations.defaults .Values.podAnnotations.oversight) }}
{{- toYaml . | nindent 8 }}
{{- end }}
      labels:
        {{- include "oversight.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "oversight.serviceAccountName" . }}
{{- $securityContextEnabled := .Values.securityContext.enabled }}
{{- $securityContext := default .Values.securityContext.default .Values.securityContext.oversight }}
{{- $podSecurityContext := default .Values.securityContext.default.pod $securityContext.pod }}
{{- $containerSecurityContext := default .Values.securityContext.default.container $securityContext.container.oversight }}
{{- if $securityContextEnabled }}
      securityContext:
{{ toYaml $podSecurityContext | indent 8 }}
{{- end }}
      {{- $imageDefaults := .Values.images.defaults }}
      {{- with .Values.images.oversight }}
      {{- $secret := (default (default "" $imageDefaults.imagePullSecret) .imagePullSecret) }}
      {{- if not (eq "" $secret) }}
      imagePullSecrets:
        - name: {{ $secret | quote }}
      {{- end }}
      containers:
      - name: controller-manager
{{- if $securityContextEnabled }}
        securityContext:
{{ toYaml $containerSecurityContext | indent 12 }}
{{- end }}
        {{- $project := (default (default "trendmicrocloudone" $imageDefaults.project) .project) }}
        {{- $repository := printf "%s/%s" $project (required ".repository is required!" .repository) }}
        {{- $tag := (default $imageDefaults.tag .tag) }}
        image: {{ include "image.source" (dict "repository" $repository "registry" .registry "tag" $tag "imageDefaults" $imageDefaults "digest" .digest) }}
        imagePullPolicy: {{ default (default "Always" $imageDefaults.pullPolicy) .pullPolicy }}
        {{- end }}
        ports:
          - containerPort: 8070
        volumeMounts:
          - name: workdir
            mountPath: /var/oversight
          - name: api-key
            mountPath: /secrets
          {{- if .Values.telemetry.publicKey }}
          - name: telemetry-secret
            mountPath: /telemetry
          {{- end }}{{/* .Values.telemetry.publicKey */}}
          - name: compliance-scan-job-template
            mountPath: /etc/config
          {{- include "proxy.selfSignedCertificates.volumeMounts" . | nindent 10 }}
        args:
        - --zap-devel={{ default "false" .Values.logConfig.devel }}
        - --zap-log-level={{ include "logLevel" (list .Values.cloudOne.oversight.logLevel .) }}
        - --zap-encoder={{ default "json" .Values.logConfig.encoder }}
        - --zap-stacktrace-level={{ default "error" .Values.logConfig.stacktraceLevel }}
        - --zap-time-encoding={{ default "rfc3339" .Values.logConfig.timeEncoding }}
        - --tls-min-version={{ include "tlsConfig.minTLSVersion" .Values.tlsConfig }}
        - --tls-cipher-suites={{ include "tlsConfig.cipherSuites" .Values.tlsConfig }}
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --compliance-scan-bind-address=:8070
        {{- if gt (int .Values.replicas.oversight) 1 }}
        - --leader-elect
        {{- end }}
        - --mitigation-handler-buffer-size={{ default 50 .Values.cloudOne.oversight.mitigationHandlerBufferSize }}
        - --page-size={{ default 100 .Values.cloudOne.oversight.pageSize }}
        - --sync-period={{ default "3600s" .Values.cloudOne.oversight.syncPeriod }}
        - --enable-runtime-mitigation={{ default "false" .Values.cloudOne.runtimeSecurity.enabled }}
        - --enable-compliance-scan={{ default "false" .Values.cloudOne.complianceScan.enabled }}
        - --job-template-path=/etc/config/compliance-scan-job-template.yaml
        - --exclude-kubernetes-service-host-from-proxy={{ default "false" .Values.proxy.excludeKubernetesServiceHost }}
        - --excluded-namespaces
        {{- $excludeNS := include "namespaceExclusions" . }}
        - {{ $excludeNS | quote }}
        - --cloud-one-endpoint={{ include "container.security.endpoint" . }}
        - --network-policy-label={{ default "trendmicro" .Release.Name }}
        - --application-version=$(APPLICATION_VERSION)
        {{- if (eq .Values.cloudOne.oversight.enableNetworkPolicyCreation false) }}
        - --enable-network-policy-creation=false
        {{- end }}
        {{- if .Values.telemetry.enabled }}
        - --telemetry-endpoint={{ .Values.telemetry.endpoint }}
        - --telemetry-interval={{ .Values.telemetry.interval }}
        - --telemetry-api-key={{ default "" .Values.telemetry.apiKey }}
        {{- if .Values.telemetry.publicKey }}
        - --telemetry-key-file=/telemetry/key.pem
        {{- end }}{{/* .Values.telemetry.publicKey */}}
        {{- end }}{{/* .Values.telemetry.enabled */}}
        - --trusted-images={{ include "digest" . }}
        command:
        - /manager
        env:
        {{- include "container.security.proxy.env" . | nindent 8 }}
        - name: APPLICATION_VERSION
          value: {{ .Chart.AppVersion | quote }}
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
{{ toYaml (default .Values.resources.defaults .Values.resources.oversight) | indent 12 }}
      - {{ include "rbacProxy" (dict "securityContext" .Values.securityContext "images" .Values.images "resources" .Values.resources "customSecurityContext" .Values.securityContext.oversight "tlsConfig" .Values.tlsConfig ) | nindent 8 | trim }}
      terminationGracePeriodSeconds: 10
{{- if or .Values.nodeSelector.defaults .Values.nodeSelector.oversight }}
      nodeSelector:
{{ toYaml (default .Values.nodeSelector.defaults .Values.nodeSelector.oversight) | indent 8 }}
{{- end }}
{{- if or .Values.tolerations.defaults .Values.tolerations.oversight }}
      tolerations:
{{ toYaml (default .Values.tolerations.defaults .Values.tolerations.oversight) | indent 8 }}
{{- end }}
{{- if or .Values.affinity.defaults .Values.affinity.oversight }}
      affinity:
{{ toYaml (default .Values.affinity.defaults .Values.affinity.oversight) | indent 8 }}
{{- end }}
{{- $classname := (default (default "" .Values.priorityClassName.default ) .Values.priorityClassName.oversight) }}
{{- if not (eq "" $classname) }}
      priorityClassName: "{{ $classname }}"
{{- end }}
      restartPolicy: Always
      volumes:
        - name: workdir
          emptyDir:
            sizeLimit: 50Mi
        - name: api-key
          secret:
            secretName: {{ template "container.security.fullname" . }}-auth
        - name: rbac-proxy-certs
          secret:
            secretName: {{ template "kubeRbacProxy.fullname" . }}-tls-certificate
        {{- if .Values.telemetry.publicKey }}
        - name: telemetry-secret
          secret:
            secretName: {{ template "container.security.fullname" . }}-telemetry
            items:
            - key: publicKey
              path: key.pem
        {{- end }}{{/* .Values.telemetry.publicKey */}}
        - name: compliance-scan-job-template
          configMap:
            name: {{ template "container.security.name" . }}-oversight-controller-config
            items:
              - key: compliance-scan-job-template.yaml
                path: compliance-scan-job-template.yaml
        {{- include "proxy.selfSignedCertificates.volumes" . | nindent 8 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "oversight.labels" . | nindent 4 }}
  name: trendmicro-oversight-controller-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    {{- include "oversight.selectorLabels" . | nindent 4 }}

{{ if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: oversight-controller-networkpolicy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oversight.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "oversight.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from: # any -- this is for metrics
      ports:
        - protocol: TCP
          port: 8443
    - from: # any -- this should just be kubelet for health probes
      ports:
        - protocol: TCP
          port: 8081
    - from: # allows traffic from compliance scan jobs
      - podSelector:
          matchLabels:
            {{- include "complianceScanJob.selectorLabels" . | nindent 12 }}
      ports:
        - protocol: TCP
          port: 8070
{{- end }}

{{ if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oversight.serviceAccountName" . }}
  labels:
    {{- include "oversight.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.oversight.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "container.security.name" . }}-oversight-controller-config
  labels:
    {{- include "oversight.labels" . | nindent 4 }}
data:
  compliance-scan-job-template.yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      labels:
        {{- include "complianceScanJob.labels" . | nindent 8 }}
      annotations:
        {{- with (default .Values.podAnnotations.defaults .Values.podAnnotations.complianceScanJob) }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      namespace: {{ .Release.Namespace }}
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: {{ .Values.cloudOne.complianceScan.activeDeadlineSeconds }}
      ttlSecondsAfterFinished: 60
      template:
        metadata:
          labels:
            {{- include "complianceScanJob.labels" . | nindent 12 }}
          annotations:
            {{- with (default .Values.podAnnotations.defaults .Values.podAnnotations.complianceScanJob) }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          hostPID: true
          serviceAccountName: {{ include "complianceScanJob.serviceAccountName" . }}
          restartPolicy: Never
          {{- $imageDefaults := .Values.images.defaults }}
          {{- with .Values.images.complianceScanJob }}
          {{- $secret := (default (default "" $imageDefaults.imagePullSecret) .imagePullSecret) }}
          {{- if not (eq "" $secret) }}
          imagePullSecrets:
            - name: {{ $secret | quote }}
          {{- end }}
          containers:
          - name: compliance-scan-job
            {{- $project := (default (default "trendmicrocloudone" $imageDefaults.project) .project) }}
            {{- $repository := printf "%s/%s" $project (required ".repository is required!" .repository) }}
            {{- $tag := (default $imageDefaults.tag .tag) }}
            image: {{ include "image.source" (dict "repository" $repository "registry" .registry "tag" $tag "imageDefaults" $imageDefaults "digest" .digest) }}
            imagePullPolicy: {{ default (default "Always" $imageDefaults.pullPolicy) .pullPolicy }}
            {{- end }}
            args:
            - scan
            env:
            - name: LOG_LEVEL
              value: info
            resources:
{{ toYaml (default .Values.resources.defaults .Values.resources.complianceScanner) | indent 14 }}
            volumeMounts:
              - name: var-lib-kubelet
                mountPath: /var/lib/kubelet
                readOnly: true
              - name: etc-systemd
                mountPath: /etc/systemd
                readOnly: true
              - name: etc-kubernetes
                mountPath: /etc/kubernetes
                readOnly: true
              - name: etc-default
                mountPath: /etc/default
                readOnly: true
              - name: home-kubernetes
                mountPath: /home/kubernetes
                readOnly: true
              - name: var-lib-cni
                mountPath: /var/lib/cni
                readOnly: true
              - name: var-lib-etcd
                mountPath: /var/lib/etcd
                readOnly: true
              - name: var-lib-kube-scheduler
                mountPath: /var/lib/kube-scheduler
                readOnly: true
              - name: var-lib-kube-controller-manager
                mountPath: /var/lib/kube-controller-manager
                readOnly: true
              - name: lib-systemd
                mountPath: /lib/systemd/
                readOnly: true
                # /usr/local/mount-from-host/bin is mounted to access kubectl / kubelet, for auto-detecting the Kubernetes version.
                # You can omit this mount if you specify --version as part of the command.
              - name: usr-bin
                mountPath: /usr/local/mount-from-host/bin
                readOnly: true
              - name: etc-cni-netd
                mountPath: /etc/cni/net.d/
                readOnly: true
              - name: opt-cni-bin
                mountPath: /opt/cni/bin/
                readOnly: true
              - name: etc-passwd
                mountPath: /etc/passwd
                readOnly: true
              - name: etc-group
                mountPath: /etc/group
                readOnly: true
              - name: var-vcap-jobs
                mountPath: /var/vcap/jobs
                readOnly: true
              - name: var-vcap-packages
                mountPath: /var/vcap/packages
                readOnly: true
              - name: var-vcap-store-etcd
                mountPath: /var/vcap/store/etcd
                readOnly: true
              - name: var-vcap-sys
                mountPath: /var/vcap/sys
                readOnly: true
          volumes:
            - name: var-lib-kubelet
              hostPath:
                path: "/var/lib/kubelet"
                type: DirectoryOrCreate
            - name: etc-systemd
              hostPath:
                path: "/etc/systemd"
                type: DirectoryOrCreate
            - name: etc-kubernetes
              hostPath:
                path: "/etc/kubernetes"
                type: DirectoryOrCreate
            - name: etc-default
              hostPath:
                path: "/etc/default"
                type: DirectoryOrCreate
            - name: home-kubernetes
              hostPath:
                path: "/home/kubernetes"
                type: DirectoryOrCreate
            - name: var-lib-cni
              hostPath:
                path: "/var/lib/cni"
                type: DirectoryOrCreate
            - name: var-lib-etcd
              hostPath:
                path: "/var/lib/etcd"
                type: DirectoryOrCreate
            - name: var-lib-kube-scheduler
              hostPath:
                path: "/var/lib/kube-scheduler"
                type: DirectoryOrCreate
            - name: var-lib-kube-controller-manager
              hostPath:
                path: "/var/lib/kube-controller-manager"
                type: DirectoryOrCreate
            - name: lib-systemd
              hostPath:
                path: "/lib/systemd"
                type: DirectoryOrCreate
            - name: usr-bin
              hostPath:
                path: "/usr/bin"
                type: DirectoryOrCreate
            - name: etc-cni-netd
              hostPath:
                path: "/etc/cni/net.d/"
                type: DirectoryOrCreate
            - name: opt-cni-bin
              hostPath:
                path: "/opt/cni/bin/"
                type: DirectoryOrCreate
            - name: etc-passwd
              hostPath:
                path: "/etc/passwd"
                type: FileOrCreate
            - name: etc-group
              hostPath:
                path: "/etc/group"
                type: FileOrCreate
            - name: var-vcap-jobs
              hostPath:
                path: "/var/vcap/jobs"
                type: DirectoryOrCreate
            - name: var-vcap-packages
              hostPath:
                path: "/var/vcap/packages"
                type: DirectoryOrCreate
            - name: var-vcap-store-etcd
              hostPath:
                path: "/var/vcap/store/etcd"
                type: DirectoryOrCreate
            - name: var-vcap-sys
              hostPath:
                path: "/var/vcap/sys"
                type: DirectoryOrCreate
{{- end }}
