{{- if eq true .Values.cloudOne.vulnerabilityScanning.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: scan-manager-role
  labels:
    {{- include "scanManager.labels" . | nindent 4 }}
rules:
- apiGroups:
  - cloudone.trendmicro.com
  resources:
  - workloadimages
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scan-manager-rolebinding
  labels:
    {{- include "scanManager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scan-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "scanManager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
