{{- if eq true .Values.cloudOne.vulnerabilityScanning.enabled }}
{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "workloadOperator.serviceAccountName" . }}
  labels:
    {{- include "workloadOperator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.workloadOperator.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trendmicro-workload-operator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "workloadOperator.labels" . | nindent 4 }}
spec:
  replicas: {{ default 1 .Values.replicas.workloadOperator }}
  selector:
    matchLabels:
      {{- include "workloadOperator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/auth: {{ include "container.security.auth.secret" . | sha256sum }}
{{- with (default .Values.podAnnotations.defaults .Values.podAnnotations.workloadOperator) }}
{{- toYaml . | nindent 8 }}
{{- end }}
      labels:
        {{- include "workloadOperator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "workloadOperator.serviceAccountName" . }}
{{- $securityContextEnabled := .Values.securityContext.enabled }}
{{- $securityContext := default .Values.securityContext.default .Values.securityContext.workloadOperator }}
{{- $podSecurityContext := default .Values.securityContext.default.pod $securityContext.pod }}
{{- $containerSecurityContext := default .Values.securityContext.default.container $securityContext.container.workloadOperator }}
{{- if $securityContextEnabled }}
      securityContext:
{{ toYaml $podSecurityContext | indent 8 }}
{{- end }}
      {{- $imageDefaults := .Values.images.defaults }}
      {{- with .Values.images.workloadOperator }}
      {{- $secret := (default (default "" $imageDefaults.imagePullSecret) .imagePullSecret) }}
      {{- if not (eq "" $secret) }}
      imagePullSecrets:
        - name: {{ $secret | quote }}
      {{- end }}
      containers:
      - name: trendmicro-workload-operator
{{- if $securityContextEnabled }}
        securityContext:
{{ toYaml $containerSecurityContext | indent 12 }}
{{- end }}
        {{- $project := (default (default "trendmicrocloudone" $imageDefaults.project) .project) }}
        {{- $repository := printf "%s/%s" $project (required ".repository is required!" .repository) }}
        {{- $tag := (default $imageDefaults.tag .tag) }}
        image: {{ include "image.source" (dict "repository" $repository "registry" .registry "tag" $tag "imageDefaults" $imageDefaults "digest" .digest) }}
        imagePullPolicy: {{ default (default "Always" $imageDefaults.pullPolicy) .pullPolicy }}
        {{- end }}
        args:
        - --cloud-one-endpoint={{ include "container.security.endpoint" . }}
        - --excluded-namespaces
        {{- $excludeNS := (default (list) .Values.cloudOne.exclusion.namespaces) }}
        - {{ $excludeNS | join "," | quote }}
        - --workload-controller-instance-name={{ .Release.Name }}
        - --log-level
        - debug
        command:
        - /app/workload-operator
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- include "container.security.proxy.env" . | nindent 8 }}
        volumeMounts:
          - mountPath: /secrets
            name: api-key
        resources:
{{ toYaml (default .Values.resources.defaults .Values.resources.workloadOperator) | indent 12 }}
      volumes:
        - name: api-key
          secret:
            secretName: {{ template "container.security.fullname" . }}-auth
      terminationGracePeriodSeconds: 10
      nodeSelector:
{{ toYaml (default .Values.nodeSelector.defaults .Values.nodeSelector.workloadOperator) | indent 8 }}
      tolerations:
{{ toYaml (default .Values.tolerations.defaults .Values.tolerations.workloadOperator) | indent 8 }}
      affinity:
{{ toYaml (default .Values.affinity.defaults .Values.affinity.workloadOperator) | indent 8 }}
{{- $classname := (default (default "" .Values.priorityClassName.default ) .Values.priorityClassName.workloadOperator) }}
{{- if not (eq "" $classname) }}
      priorityClassName: "{{ $classname }}"
{{- end }}
      restartPolicy: Always
{{- end }}

